name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:

      - name: Set up Go 1.21
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          go mod download
          go install golang.org/x/tools/cmd/goimports@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run go vet
        run: go vet ./...

      - name: Run goimports
        run: goimports -w . && git diff --exit-code

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Run tests with race detector and coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt